---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
  namespace: default
  labels:
    app: deployment-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment-1
  template:
    metadata:
      labels:
        app: deployment-1
    spec:
      containers:
      - name: flask-app-sha256-1
        image: us-central1-docker.pkg.dev/cloud-461215/my-repo/flask-app@sha256:25471b741c85cfb766e5ac3baebfc40fbe4be8ee5c459e976f6cc7cdaa4c7d1d
        ports:
        - containerPort: 5000
        env:
        - name: NEWS_API_KEY
          valueFrom:
            secretKeyRef:
              name: news-api-key-secret
              key: NEWS_API_KEY
        - name: BQ_PROJECT
          value: cloud-461215
        - name: BQ_DATASET
          value: news_dataset
        - name: BQ_TABLE
          value: articles
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: deployment-1-hpa-uw9h
  namespace: default
  labels:
    app: deployment-1
spec:
  scaleTargetRef:
    kind: Deployment
    name: deployment-1
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-1-service
  namespace: default
  labels:
    app: deployment-1
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: deployment-1
  type: LoadBalancer
  loadBalancerIP: ""
